repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: check-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace
    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: 'v9.12.0' # Use the sha / tag you want to point at
      hooks:
          - id: eslint
            files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
            types: [file]
